// <auto-generated />
using CIDM_3315_Final_Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIDM_3315_Final_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("CIDM_3315_Final_Project.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RarityID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TypeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemID");

                    b.HasIndex("RarityID");

                    b.HasIndex("TypeID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("CIDM_3315_Final_Project.Models.Rarity", b =>
                {
                    b.Property<int>("RarityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("RarityID");

                    b.ToTable("Rarity");
                });

            modelBuilder.Entity("CIDM_3315_Final_Project.Models.Type", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("TypeID");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("CIDM_3315_Final_Project.Models.Item", b =>
                {
                    b.HasOne("CIDM_3315_Final_Project.Models.Rarity", null)
                        .WithMany("Items")
                        .HasForeignKey("RarityID");

                    b.HasOne("CIDM_3315_Final_Project.Models.Type", null)
                        .WithMany("Items")
                        .HasForeignKey("TypeID");
                });

            modelBuilder.Entity("CIDM_3315_Final_Project.Models.Rarity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CIDM_3315_Final_Project.Models.Type", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
